apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: azure-
images:
  - name: ghcr.io/your-user/finance-app
    newName: REPLACE_WITH_ACR/finance-app
    newTag: latest




