apiVersion: v1
kind: Secret
metadata:
  name: finance-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/finance?schema=public
  API_TOKEN: change-me
  CORS_ORIGIN: "http://4.249.114.84"
  NEXTAUTH_SECRET: "change-me-secret"
  NEXTAUTH_URL: "http://4.249.114.84"




